baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Vibetracker Site'
theme = 'ananke'

[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1

[[menu.main]]
  name = 'Compare'
  url = '/compare/'
  weight = 2
